backend:
  name: github
  repo: V1RE/Cosmos
  base_url: https://netlify-cms-oauth-bay.vercel.app/
  branch: main
local_backend: true
media_folder: 'public/uploads'
public_folder: '/uploads'
collections:
  - name: pages
    label: Pages
    folder: src/data/pages
    slug: '{{slug}}'
    create: true
    fields:
      - { label: 'Titel', name: 'title', widget: 'string' }
      - { label: 'Slug', name: 'slug', widget: 'string' }
  - name: 'navigations'
    label: 'Navigations'
    files:
      - file: 'src/data/navs/mainmenu.json'
        label: 'Mainmenu'
        name: 'mainmenu'
        extension: 'json'
        format: 'json'
        editor:
          preview: false
        fields:
          - label: 'Item'
            name: 'items'
            widget: 'list'
            min: 1
            summary: '{{fields.page}}'
            fields:
              - { label: 'Title', name: 'title', widget: 'string' }
              - label: 'Page'
                name: 'slug'
                widget: 'relation'
                collection: 'pages'
                search_fields: ['title']
                value_field: 'slug'
                display_fields: ['title']
